#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for huawei_s_l2_interfaces
"""


from __future__ import absolute_import, division, print_function
__metaclass__ = type


ANSIBLE_METADATA = {'metadata_version': '1.0',
                    'status': ['preview'],
                    'supported_by': 'community'}

DOCUMENTATION = """
---
module: huawei_s_l2_interfaces
version_added: 2.9
short_description: Manage Layer-2 interface on Huawei S Series devices.
description: This module provides declarative management of Layer-2 interface on Huawei S Series devices.
author: Aleksandr Natov (@pahedu)
notes:
  - Tested against VRP V200R010C00SPC600
  - This module works with connection C(network_cli).
options:
  config:
    description: A dictionary of Layer-2 interface options
    type: list
    elements: dict
    suboptions:
      name:
        description:
        - Full name of the interface excluding any logical unit number, i.e. GigabitEthernet0/0/1.
        type: str
        required: True
      access:
        description:
        - Switchport mode access command to configure the interface as a layer 2 access.
        type: dict
        suboptions:
          vlan:
            description:
            - Configure given VLAN in access port. It's used as the access VLAN ID.
            type: int
      trunk:
        description:
        - Switchport mode trunk command to configure the interface as a Layer 2 trunk.
        type: dict
        suboptions:
          allowed_vlans:
            description:
            - List of allowed VLANs in a given trunk port. These are the only VLANs that will be
              configured on the trunk.
            type: list
          native_vlan:
            description:
            - Native VLAN to be configured in trunk port. It's used as the trunk native VLAN ID.
            type: int
      hybrid:
        description:
        - Switchport mode hybrid command to configure the interface as a Layer 2 hybrid.
        type: dict
        suboptions:
          allowed_vlans:
            description:
            - List of allowed VLANs in a given hybrid port. These are the only VLANs that will be
              configured on the hybrid.
            type: list
          native_vlan:
            description:
            - Native VLAN to be configured in hybrid port. It's used as the hybrid native VLAN ID.
            type: int
  state:
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
    description:
    - The state of the configuration after module completion
    type: str
"""

EXAMPLES = """
---

# Using merged

# Before state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        trunk        1     1-4094
#GigabitEthernet0/0/3        hybrid       5     1-9 11-4094
#GigabitEthernet0/0/4        access       10    -

- name: Merge provided configuration with device configuration
  huawei_s_l2_interfaces:
    config:
      - name: GigabitEthernet0/0/2
        access:
          vlan: 10
      - name: GigabitEthernet0/0/3
        trunk:
          allowed_vlan: 10-20,40
          native_vlan: 20
      - name: GigabitEthernet0/0/4
        hybrid:
          allowed_vlans: 10-20,30,40-50,65
          native_vlan: 30
    state: merged

# After state:
# ------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        trunk        20    10-20 40
#GigabitEthernet0/0/3        access       10    -
#GigabitEthernet0/0/4        hybrid       30    10-20 30 40-50 65

# Using replaced

# Before state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        trunk        20    10-20 40
#GigabitEthernet0/0/3        access       10    -
#GigabitEthernet0/0/4        hybrid       30    10-20 30 40-50 65

- name: Replaces device configuration of listed l2 interfaces with provided configuration
  huawei_s_l2_interfaces:
    config:
      - name: GigabitEthernet0/0/2
        trunk:
          allowed_vlans: 20-25,40
          native_vlan: 20
    state: replaced

# After state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        trunk        20    20-25 40
#GigabitEthernet0/0/3        access       10    -
#GigabitEthernet0/0/4        hybrid       30    10-20 30 40-50 65

# Using overridden

# Before state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        trunk        20    20-25 40
#GigabitEthernet0/0/3        access       10    -
#GigabitEthernet0/0/4        hybrid       30    10-20 30 40-50 65

- name: Override device configuration of all l2 interfaces with provided configuration
  huawei_s_l2_interfaces:
    config:
      - name: GigabitEthernet0/0/2
        access:
          vlan: 20
    state: overridden

# After state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        access       20    -
#GigabitEthernet0/0/3        auto         1     1-4094
#GigabitEthernet0/0/4        auto         1     1-4094


# Using Deleted

# Before state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        access       20    -
#GigabitEthernet0/0/3        auto         1     1-4094
#GigabitEthernet0/0/4        auto         1     1-4094

- name: Delete L2 interfaces as in given arguments
  huawei_s_l2_interfaces:
    config:
      - name: GigabitEthernet0/0/2
    state: deleted

# After state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        auto         1     1-4094
#GigabitEthernet0/0/3        auto         1     1-4094
#GigabitEthernet0/0/4        auto         1     1-4094


# Using Deleted without any config passed
#"(NOTE: This will delete all of configured resource module attributes from each configured interface)"

# Before state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        auto         1     1-4094
#GigabitEthernet0/0/3        auto         1     1-4094
#GigabitEthernet0/0/4        auto         1     1-4094

- name: Delete  L2 interfaces as in given arguments
  huawei_s_l2_interfaces:
    state: deleted

# After state:
# -------------
#
#[HUAWEI]display port vlan
#GigabitEthernet0/0/2        auto         1     1-4094
#GigabitEthernet0/0/3        auto         1     1-4094
#GigabitEthernet0/0/4        auto         1     1-4094

"""

RETURN = """
before:
  description: The configuration as structured data prior to module invocation.
  returned: always
  type: list
  sample: The configuration returned will always be in the same format of the parameters above.
after:
  description: The configuration as structured data after module completion.
  returned: when changed
  type: list
  sample: The configuration returned will always be in the same format of the parameters above.
commands:
  description: The set of commands pushed to the remote device
  returned: always
  type: list
  sample: ['interface GigabitEthernet0/0/1', 'port link-type access', port default vlan 20']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.network.huawei_s_series.argspec.l2_interfaces.l2_interfaces import L2_InterfacesArgs
from ansible.module_utils.network.huawei_s_series.config.l2_interfaces.l2_interfaces import L2_Interfaces


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    required_if = [('state', 'merged', ('config',)),
                   ('state', 'replaced', ('config',)),
                   ('state', 'overridden', ('config',))]

    module = AnsibleModule(argument_spec=L2_InterfacesArgs.argument_spec,
                           required_if=required_if,
                           supports_check_mode=True)

    result = L2_Interfaces(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
