#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for huawei_s_interfaces
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {'metadata_version': '1.0',
                    'status': ['preview'],
                    'supported_by': 'community'}


DOCUMENTATION = """
---
module: huawei_s_interfaces
version_added: 2.9
short_description: Manages interface attributes of Huawei S Series network devices
description: This module manages the interface attributes of Huawei S Series network devices.
author: Aleksandr Natov (@pahedu)
notes:
- Tested against VRP V200R010C00SPC600
- This module works with connection C(network_cli).
options:
  config:
    description: A dictionary of interface options
    type: list
    suboptions:
      name:
        description:
        - Full name of interface, e.g. GigabitEthernet0/0/2, LoopBack999.
        type: str
        required: True
      description:
        description:
        - Interface description.
        type: str
      enabled:
        description:
        - Administrative state of the interface.
        - Set the value to C(true) to administratively enable the interface or C(false) to disable it.
        type: bool
        default: True
      speed:
        description:
        - Interface link speed. Applicable for GigabitEthernet interfaces only.
        type: str
      mtu:
        description:
        - MTU for a specific interface.
        - Refer to vendor documentation for valid values.
        type: int
      duplex:
        description:
        - Interface link status. Applicable for GigabitEthernet interfaces only, either in half duplex,
          full duplex or in automatic state which negotiates the duplex automatically.
        type: str
        choices: ['full', 'half']
      negotiation:
        description:
        - Interface speed and duplex negotiation.
        type: bool
  state:
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
    description:
    - The state of the configuration after module completion
    type: str
"""

EXAMPLES = """
---

# Using merged

# Before state:
# -------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : DOWN
#Description:
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
#

- name: Merge provided configuration with device configuration
  huawei_s_interfaces:
    config:
      - name: GigabitEthernet0/0/2
        description: 'Configured and Merged by Ansible Network'
        enabled: True
      - name: GigabitEthernet0/0/3
        description: 'Configured and Merged by Ansible Network'
        mtu: 2800
        enabled: False
        speed: 100
        duplex: half
        negotiation: False
    state: merged

# After state:
# ------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:Configured and Merged by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : Administratively DOWN
#Description:Configured and Merged by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 2800
#Speed : 100,    Loopback: NONE
#Duplex: HALF,   Negotiation: DISABLE
#Mdi   : AUTO,   Flow-control: DISABLE

# Using replaced

# Before state:
# -------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:Configured and Merged by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : Administratively DOWN
#Description:Configured and Merged by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 2800
#Speed : 100,    Loopback: NONE
#Duplex: HALF,   Negotiation: DISABLE
#Mdi   : AUTO,   Flow-control: DISABLE

- name: Replaces device configuration of listed interfaces with provided configuration
  huawei_s_interfaces:
    config:
      - name: GigabitEthernet0/0/3
        description: 'Configured and Replaced by Ansible Network'
        enabled: False
        duplex: full
        mtu: 2500
        speed: 1000
        negotiation: True
    state: replaced

# After state:
# -------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:Configured and Merged by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : Administratively DOWN
#Line protocol current state : DOWN
#Description:Configured and Replaced by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 2500
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE

# Using overridden

# Before state:
# -------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:Configured and Merged by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : Administratively DOWN
#Line protocol current state : DOWN
#Description:Configured and Replaced by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 2500
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE


- name: Override device configuration of all interfaces with provided configuration
  huawei_s_interfaces:
    config:
      - name: GigabitEthernet0/0/2
        description: 'Configured and Overridden by Ansible Network'
        negotiation: False
        speed: 100
      - name: GigabitEthernet0/0/3
        description: 'Configured and Overridden by Ansible Network'
        enabled: False
        negotiation: True
        duplex: full
        mtu: 2000
    state: overridden

# After state:
# -------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:Configured and Overridden by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 100,    Loopback: NONE
#Duplex: FULL,   Negotiation: DISABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : Administratively DOWN
#Description:Configured and Overridden by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 2000
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE

# Using Deleted

# Before state:
# -------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:Configured and Overridden by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 100,    Loopback: NONE
#Duplex: FULL,   Negotiation: DISABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : Administratively DOWN
#Description:Configured and Overridden by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 2000
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE

- name: "Delete module attributes of given interfaces (Note: This won't delete the interface itself)"
  huawei_s_interfaces:
    config:
      - name: GigabitEthernet0/0/2
    state: deleted

# After state:
# -------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : Administratively DOWN
#Description:Configured and Overridden by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 2000
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE


# Using Deleted without any config passed
#"(NOTE: This will delete all of configured resource module attributes from each configured interface)"

# Before state:
# -------------
#
#[HUAWEI]display interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : Administratively DOWN
#Description:Configured and Overridden by Ansible Network
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 2000
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE

- name: "Delete module attributes of all interfaces (Note: This won't delete the interface itself)"
  huawei_s_interfaces:
    state: deleted

# After state:
# -------------
#
#[HUAWEI]display  interface
##
#GigabitEthernet0/0/2 current state : DOWN
#Description:
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE
##
#GigabitEthernet0/0/3 current state : DOWN
#Description:
#PVID :    1, TPID : 8100(Hex), The Maximum Frame Length is 9216
#Speed : 1000,   Loopback: NONE
#Duplex: FULL,   Negotiation: ENABLE
#Mdi   : AUTO,   Flow-control: DISABLE

"""

RETURN = """
before:
  description: The configuration as structured data prior to module invocation.
  returned: always
  type: list
  sample: The configuration returned will always be in the same format of the parameters above.
after:
  description: The configuration as structured data after module completion.
  returned: when changed
  type: list
  sample: The configuration returned will always be in the same format of the parameters above.
commands:
  description: The set of commands pushed to the remote device
  returned: always
  type: list
  sample: ['interface GigabitEthernet 0/0/1', 'description This is test', 'speed 100']
"""

from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.network.huawei_s_series.argspec.interfaces.interfaces import InterfacesArgs
from ansible.module_utils.network.huawei_s_series.config.interfaces.interfaces import Interfaces


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    required_if = [('state', 'merged', ('config',)),
                   ('state', 'replaced', ('config',)),
                   ('state', 'overridden', ('config',))]

    module = AnsibleModule(argument_spec=InterfacesArgs.argument_spec,
                           required_if=required_if,
                           supports_check_mode=True)

    result = Interfaces(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
