#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for huawei_s_lacp_interfaces
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'community'
}


DOCUMENTATION = """
---
module: huawei_s_lacp_interfaces
version_added: 2.9
short_description: Manage Link Aggregation Control Protocol (LACP) on Huawei S Series devices interface.
description: This module provides declarative management of LACP on Huawei S Series network devices lacp_interfaces.
author: Aleksandr Natov (@pahedu)
notes:
  - Tested against VRP V200R010C00SPC600
  - This module works with connection C(network_cli),
options:
  config:
      description: A dictionary of LACP lacp_interfaces option
      type: list
      elements: dict
      suboptions:
        name:
          description:
          - Name of the Interface for configuring LACP.
          type: str
          required: True
        max_bundle:
          description:
          - LACP maximum number of ports to bundle in this port channel.
          - Refer to vendor documentation for valid port values.
          type: int
  state:
    description:
    - The state of the configuration after module completion
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
"""

EXAMPLES = """

# Using merged
#
# Before state:
# -------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 8
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1


- name: Merge provided configuration with device configuration
  huawei_s_lacp_interfaces:
    config:
      - name: Eth-Trunk1
        max_bundle: 5
    state: merged

# After state:
# ------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 5
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1


# Using overridden
#
# Before state:
# -------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 5
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1

- name: Override device configuration of all lacp_interfaces with provided configuration
  huawei_s_lacp_interfaces:
    config:
      - name: Eth-Trunk1
        max_bundle: 2
    state: overridden

# After state:
# ------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 2
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1

# Using replaced
#
# Before state:
# -------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 2
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1

- name: Replaces device configuration of listed lacp_interfaces with provided configuration
  huawei_s_lacp_interfaces:
    config:
      - name: Eth-Trunk1
        max_bundle: 4
    state: replaced

# After state:
# ------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 4
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1

# Using Deleted
#
# Before state:
# -------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 4
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1


- name: "Delete LACP attributes of given interfaces (Note: This won't delete the interface itself)"
  huawei_s_lacp_interfaces:
    config:
      - name: Eth-Trunk1
    state: deleted

# After state:
# -------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 8
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1
# Using Deleted without any config passed
# "(NOTE: This will delete all of configured LLDP module attributes)"
#
# Before state:
# -------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 4
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1

- name: "Delete LACP attributes for all configured interfaces (Note: This won't delete the interface itself)"
  huawei_s_lacp_interfaces:
    state: deleted

# After state:
# -------------
#
#[HUAWEI]display eth-trunk
#Eth-Trunk1's state information is:
#Local:
#LAG ID: 1                   WorkingMode: LACP
#Preempt Delay: Disabled     Hash arithmetic: According to SIP-XOR-DIP
#System Priority: 32768      System ID: a08c-f8f6-7900
#Least Active-linknumber: 1  Max Active-linknumber: 4
#Operate status: down        Number Of Up Port In Trunk: 0
#--------------------------------------------------------------------------------
#ActorPortName          Status   PortType PortPri PortNo PortKey PortState Weight
#GigabitEthernet0/0/10  Unselect 1GE      32768   1      305     10100010  1
#GigabitEthernet0/0/11  Unselect 1GE      32768   2      305     10100010  1

"""

RETURN = """
before:
  description: The configuration as structured data prior to module invocation.
  returned: always
  type: list
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The configuration as structured data after module completion.
  returned: when changed
  type: list
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['interface Eth-Trunk1', 'max active-linknumber 5']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.network.huawei_s_series.argspec.lacp_interfaces.lacp_interfaces import Lacp_InterfacesArgs
from ansible.module_utils.network.huawei_s_series.config.lacp_interfaces.lacp_interfaces import Lacp_Interfaces


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    required_if = [('state', 'merged', ('config',)),
                   ('state', 'replaced', ('config',)),
                   ('state', 'overridden', ('config',))]

    module = AnsibleModule(argument_spec=Lacp_InterfacesArgs.argument_spec,
                           required_if=required_if,
                           supports_check_mode=True)

    result = Lacp_Interfaces(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
