#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for huawei_s_vlans
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type


ANSIBLE_METADATA = {
    'metadata_version': '1.0',
    'status': ['preview'],
    'supported_by': 'community'
}

DOCUMENTATION = """
module: huawei_s_vlans
version_added: 2.9
short_description: Manage VLANs on Huawei S Series devices.
description: This module provides declarative management of VLANs on Huawei S series network devices.
author: Aleksandr Natov (@pahedu)
notes:
  - Tested against VRP V200R010C00SPC600
  - This module works with connection C(network_cli).
options:
  config:
    description: A dictionary of VLANs options
    type: list
    elements: dict
    suboptions:
      name:
        description:
        - Ascii name of the VLAN.
        - NOTE, I(name) should not be named/appended with I(default) as it is reserved for device default vlans.
        type: str
      vlan_id:
        description:
        - ID of the VLAN. Range 1-4094
        type: int
        required: True
      state:
        description:
        - Operational state of the VLAN
        type: str
        choices:
        - active
        - suspend
  state:
    description:
    - The state of the configuration after module completion
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
"""
EXAMPLES = """
---
# Using merged

# Before state:
# -------------
#
#<HUAWEI>display vlan
#The total number of VLANs is: 1
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default



- name: Merge provided configuration with device configuration
  huawei_s_vlans:
    config:
      - name: Vlan_10
        vlan_id: 10
      - name: Vlan_20
        vlan_id: 20
      - name: Vlan_30
        vlan_id: 30
    state: merged

# After state:
# ------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 4
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#10   common
#20   common
#30   common
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default
#10   enable  default       enable  disable    Vlan_10
#20   enable  default       enable  disable    Vlan_20
#30   enable  default       enable  disable    Vlan_30


# Using overridden

# Before state:
# -------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 4
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#10   common
#20   common
#30   common
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default
#10   enable  default       enable  disable    Vlan_10
#20   enable  default       enable  disable    Vlan_20
#30   enable  default       enable  disable    Vlan_30

- name: Override device configuration of all VLANs with provided configuration
  huawei_s_vlans:
    config:
      - name: New_vlan_10
        vlan_id: 10
    state: overridden

# After state:
# ------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 2
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#10   common  UT:GE0/0/2(D)      GE0/0/3(D)      GE0/0/4(D)
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default
#10   enable  default       enable  disable    New_vlan_10


# Using replaced

# Before state:
# -------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 4
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#10   common
#20   common
#30   common
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default
#10   enable  default       enable  disable    Vlan_10
#20   enable  default       enable  disable    Vlan_20
#30   enable  default       enable  disable    Vlan_30

- name: Replaces device configuration of listed VLANs with provided configuration
  huawei_s_vlans:
    config:
      - vlan_id: 20
        name: Test_VLAN20
      - vlan_id: 30
        name: Test_VLAN30
    state: replaced

# After state:
# ------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 4
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#10   common  UT:GE0/0/2(D)      GE0/0/3(D)      GE0/0/4(D)
#20   common
#30   common
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default
#10   enable  default       enable  disable    Vlan_10
#20   enable  default       enable  disable    Test_VLAN20
#30   enable  default       enable  disable    Test_VLAN30


# Using deleted

# Before state:
# -------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 4
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#10   common  UT:GE0/0/2(D)      GE0/0/3(D)      GE0/0/4(D)
#20   common
#30   common
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default
#10   enable  default       enable  disable    Vlan_10
#20   enable  default       enable  disable    Vlan_20
#30   enable  default       enable  disable    Vlan_30

- name: Delete attributes of given VLANs
  huawei_s_vlans:
    config:
      - vlan_id: 10
      - vlan_id: 20
    state: deleted

# After state:
# -------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 2
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#30   common
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default
#30   enable  default       enable  disable    Vlan_30


# Using Deleted without any config passed
#"(NOTE: This will delete all of configured vlans attributes)"

# Before state:
# -------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 2
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#30   common
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default
#30   enable  default       enable  disable    Vlan_30

- name: Delete attributes of ALL VLANs
  huawei_s_vlans:
    state: deleted

# After state:
# -------------
#
#[HUAWEI]display vlan
#The total number of VLANs is: 1
#--------------------------------------------------------------------------------
#U: Up;         D: Down;         TG: Tagged;         UT: Untagged;
#MP: Vlan-mapping;               ST: Vlan-stacking;
##: ProtocolTransparent-vlan;    *: Management-vlan;
#--------------------------------------------------------------------------------
#
#VID  Type    Ports
#--------------------------------------------------------------------------------
#1    common  UT:GE0/0/1(U)      GE0/0/5(D)      GE0/0/6(D)      GE0/0/7(D)
#                GE0/0/8(D)      GE0/0/9(D)      GE0/0/10(D)     GE0/0/11(D)
#                GE0/0/12(D)     GE0/0/13(D)     GE0/0/14(D)     GE0/0/15(D)
#                GE0/0/16(D)     GE0/0/17(D)     GE0/0/18(D)     GE0/0/19(D)
#                GE0/0/20(D)     GE0/0/21(D)     GE0/0/22(D)     GE0/0/23(D)
#                GE0/0/24(D)     GE0/0/25(D)     GE0/0/26(D)     GE0/0/27(D)
#                GE0/0/28(D)     GE0/0/29(D)     GE0/0/30(D)     GE0/0/31(D)
#                GE0/0/32(D)     GE0/0/33(D)     GE0/0/34(D)     GE0/0/35(D)
#                GE0/0/36(D)     GE0/0/37(D)     GE0/0/38(D)     GE0/0/39(D)
#                GE0/0/40(D)     GE0/0/41(D)     GE0/0/42(D)     GE0/0/43(D)
#                GE0/0/44(D)     GE0/0/45(D)     GE0/0/46(D)     GE0/0/47(D)
#                GE0/0/48(D)     XGE0/0/1(D)     XGE0/0/2(D)     XGE0/0/3(D)
#                XGE0/0/4(D)
#
#VID  Status  Property      MAC-LRN Statistics Description
#--------------------------------------------------------------------------------
#1    enable  default       enable  disable    default


"""
RETURN = """
before:
  description: The configuration as structured data prior to module invocation.
  returned: always
  type: list
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The configuration as structured data after module completion.
  returned: when changed
  type: list
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['vlan 20', 'name vlan_20']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.network.huawei_s_series.argspec.vlans.vlans import VlansArgs
from ansible.module_utils.network.huawei_s_series.config.vlans.vlans import Vlans


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    required_if = [('state', 'merged', ('config',)),
                   ('state', 'replaced', ('config',)),
                   ('state', 'overridden', ('config',))]

    module = AnsibleModule(argument_spec=VlansArgs.argument_spec,
                           required_if=required_if,
                           supports_check_mode=True)

    result = Vlans(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
